name: Deploy FastAPI To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: EC2에 FastAPI 코드 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."
          target: /home/ubuntu/fastapi-server/tobe

      - name: EC2에서 FastAPI 서버 재시작
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GOOGLE_API_KEY_FROM_SECRET=${{ secrets.GOOGLE_API_KEY }}
          script_stop: true
          timeout: 120s              # SSH 연결 유지 시간 증가
          command_timeout: 1800s     # 전체 명령 실행 시간 증가 (30분)
          script: |
            rm -rf /home/ubuntu/fastapi-server/current
            mv /home/ubuntu/fastapi-server/tobe /home/ubuntu/fastapi-server/current
            cd /home/ubuntu/fastapi-server/current

            python3 -m venv venv
            source venv/bin/activate

            pip install --upgrade pip
            pip install -r requirements.txt
            
            # --- API 키 전달 상태 집중 디버깅 ---
            echo "--- START API KEY DEBUG ---" >> output.log
            echo "Value of GOOGLE_API_KEY_FROM_SECRET as seen by script: [${GOOGLE_API_KEY_FROM_SECRET}]" >> output.log
            # 만약 위 값이 비어있다면, GitHub Secret 전달 자체에 문제가 있는 것입니다.
            
            echo "GOOGLE_API_KEY=${GOOGLE_API_KEY_FROM_SECRET}" > .env
            # 생성된 .env 파일 권한 설정 (소유자만 읽기/쓰기 가능하도록)
            chmod 600 .env
            echo ".env 파일 내용 확인 (디버깅용):" # 추가된 디버깅 라인
            cat .env >> output.log               # .env 내용을 output.log에도 기록
            echo "--- END API KEY DEBUG ---" >> output.log
            
            # pkill -f "uvicorn server:app" > /dev/null 2>&1 || true 
            # echo "Attempted to kill old uvicorn processes. This line always succeeds."

            nohup env GOOGLE_API_KEY="${GOOGLE_API_KEY_FROM_SECRET}" venv/bin/uvicorn server:app --host 0.0.0.0 --port 5000 >> output.log 2>&1 &
            sleep 15 
            
            tail -n 20 output.log # Uvicorn 시작 여부 및 간단한 에러 확인용
            
            echo "SCRIPT_DEBUG: FastAPI 실행 스크립트 주요 부분 완료. 이후 sudo 명령어들은 주석 처리됨."
            # 아래 진단 명령어들은 일단 주석 처리
            # ps aux | grep uvicorn
            # sudo lsof -i :5000 || echo "포트 5000에서 프로세스 없음"
            # sudo ufw status || echo "️ufw 비활성 상태 또는 접근 불가"
            # sudo ufw allow 5000 || echo "ufw 포트 열기 실패 또는 이미 열림"
